### ISSUE TITLE
Fix memory leaks and double-frees in example

### ISSUE THREAD

**Issue by nbigaouette** [nbigaouette/onnxruntime-rs#3]
To get something working quick, the example is not careful about memory leaks and double-frees.

Memory leaks happen, for example, a `CString` or `Vec` is constructed but then converted to a raw pointer using `into_raw()`. To properly free, one has to re-convert in the Rust type and let its `Drop` frees the memory (don't let C call `free()`). See https://doc.rust-lang.org/std/ffi/struct.CString.html#method.into_raw for reference.

Double-frees happen when either C's `free()` is called on a dropped object or when drop is called on a freed object.

```sh
❯ cargo run --example c_api_sample
[...]
Score for class [0] =  0.000045440644
Score for class [1] =  0.0038458651
Score for class [2] =  0.00012494653
Score for class [3] =  0.0011804523
Score for class [4] =  0.0013169361
Done!
c_api_sample(28315,0x10e194dc0) malloc: *** error for object 0x7fafb10b8000: pointer being freed was not allocated
c_api_sample(28315,0x10e194dc0) malloc: *** set a breakpoint in malloc_error_break to debug
```

976cac722ad09b98f7e6c875e8e94d86

When this is fixed, the full API requirement should be visible.

**Comment by mcandre** [comment]
Note that libFuzzer can identify even more memory errors in code, that Valgrind can miss.

**Comment by nbigaouette** [comment]
Yes, it's mostly a matter of time... :(
