### ISSUE TITLE
Error while reading sklearn-onnx model

### ISSUE THREAD

**Issue by Vikramardham** [nbigaouette/onnxruntime-rs#85]
I am testing out the onnxruntime library.  I have a very simple model built in Python using sklearn and I save it in the onnx format using skl2onnx library. 

python code:

```
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from skl2onnx.common.data_types import FloatTensorType
from skl2onnx import convert_sklearn, get_model_alias

digits = load_digits()
x_train, x_test, y_train, y_test = train_test_split(
    digits.data, digits.target, test_size=0.2, random_state=2)
clf = LogisticRegression()
initial_type = [('input', FloatTensorType([None, 64]))]

onx = convert_sklearn(clf, initial_types=initial_type, target_opset=11)
with open("simple_model.onnx", "wb") as f:
    f.write(onx.SerializeToString()
```

and I read the model in rust
```
    let environment = environment::Environment::builder()
        .with_name("trial")
        .with_log_level(onnxruntime::LoggingLevel::Verbose)
        .build()?;

    let _session = environment
        .new_session_builder()?
        .with_optimization_level(onnxruntime::GraphOptimizationLevel::Basic)?
        .with_model_from_file("simple_model.onnx")?
```

I get the following error while building the session in rust:

`thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `0x0`,
 right: `0x0`', /home/vikram/.cargo/registry/src/github.com-1ecc6299db9ec823/onnxruntime-0.0.12/src/session.rs:690:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

What am I doing wrong? Any help is greatly appreciated!

**Comment by harshad-dh** [comment]
Running into the same error. Were you able to find any solutions @Vikramardham ? 
Is sklearn ported model not supported ?

**Comment by tlegrave** [comment]
I'm running into a similar issue when trying to load a basic model converted with [skl2onnx](https://github.com/onnx/sklearn-onnx).

I started investigating and it seems that the error comes from the "deserialization" of the outputs of the model. Sounds like a type casting issue or something similar.

Has anyone found a solution? I'll follow my researchs and post again if I find a workaround.

**Comment by Vikramardham** [comment]
@tlegrave This is beautiful. Works for me. Thanks a lot!
